name    'marrrvin-tarantool'
version '0.1.0'
source 'git@github.com:marrrvin/puppet-tarantool.git'
author 'Sergey Orlov'
license ''
summary 'Puppet module for Tarantool'
description 'Module to configure Tarantool NoSQL database.'
project_page 'https://github.com/marrrvin/puppet-tarantool'
