name    'marrrvin-tarantool'
version '0.1.0'
source 'git@github.com:marrrvin/puppet-tarantool.git'
author 'Sergey Orlov'
license ''
summary 'Manage tarantool - a NoSQL database'
description ''
project_page 'https://github.com/marrrvin/puppet-tarantool'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
